image: python:3-slim

before_script:
  - pip install ansible ansible-lint
  - ansible-lint --version

stages:
  - ansible-lint

ansible-lint:
  stage: linting
  image: registry.gitlab.com/pipeline-components/ansible-lint:latest
  script:
    - ansible-lint --show-relpath playbooks/
